# Copyright (c) 2021, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
ARG GOLANG_VERSION=x.x.x
ARG GOLANGCI_LINT_VERSION=v2.13.2
ARG MOQ_VERSION=v0.4.0
ARG CONTROLLER_GEN_VERSION=v0.20.0
ARG CLIENT_GEN_VERSION=v0.29.2
ARG MOCKGEN_VERSION=v0.6.0
FROM golang:${GOLANG_VERSION}

# RUN go install github.com/gordonklaus/ineffassign@latest && \
#     go install github.com/client9/misspell/cmd/misspell@latest

ENV GOTOOLCHAIN=local
RUN go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@${GOLANGCI_LINT_VERSION}
RUN go install github.com/matryer/moq@${MOQ_VERSION}
RUN go install sigs.k8s.io/controller-tools/cmd/controller-gen@${CONTROLLER_GEN_VERSION}
RUN go install k8s.io/code-generator/cmd/client-gen@${CLIENT_GEN_VERSION}
RUN go install go.uber.org/mock/mockgen@${MOCKGEN_VERSION}
